axis_speed: 4  # Right thumb stick vertical
scale_speed: 4085 # 0.245 m/s / 1000, 4085 = 1 m/s, 20408 = 5 m/s
scale_speed_turbo: 20408

axis_steer: 0  # Left thumb stick horizontal
scale_steer: -0.23
scale_steer_turbo: -0.23

enable_button: 4  # Left bumper button
enable_turbo_button: 5  # Right bumper button

# BUTTONS
# A button........ button 0
# B button........ button 1
# X button........ button 2
# Y button........ button 3
# left bumper..... button 4
# right bumper.... button 5
# select button... button 6
# start button.... button 7
# xbox button..... button 8
# left stick...... button 9
# right stick..... button 10
# left D-pad...... button 11
# right D-pad..... button 12
# up D-pad........ button 13
# down D-pad...... button 14
# AXES
# left stick horizontal.... axis 0
# left stick vertical...... axis 1
# left trigger............. axis 2
# right stick horizontal... axis 3
# right stick vertical..... axis 4
# right trigger............ axis 5
# D-pad horizontal......... axis 6
# D-pad vertical........... axis 7