axis_speed: 4  # Right thumb stick vertical
scale_speed: 4085 # 0.245 m/s / 1000
scale_speed_turbo: 8170

axis_steer: 0  # Left thumb stick horizontal
scale_steer: -0.23
scale_steer_turbo: -0.23

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
